[package]
name = "aoc-2021-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = 1

[dependencies]
petgraph = "0.6"
pathfinding = "3"
slice-group-by = "0.3"
cached = { version = "0.26", default-features = false, features = ["proc_macro"] }